name: CA Certs Update
on:
  workflow_dispatch:
  schedule:
    # https://crontab.guru/every-night-at-midnight
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  update_ca_certs:
    if: startsWith(github.repository, 'adoptium/')
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5 # v2.0.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
        with:
          persist-credentials: false

      - name: Run updater
        working-directory: ./security
        run: "./mk-ca-bundle.pl"

      - uses: gr2m/create-or-update-pull-request-action@cb63b1c12a6c32d49cc613469950581413b29245 # v1.9.1
        env:
          GITHUB_TOKEN: ${{ secrets.ADOPTIUM_TEMURIN_BOT_TOKEN }}
        with:
          title: "Update CA Certs"
          body: "See details in the Meta Bug linked from the *Root Cert Inclusions into Mozilla Product Releases* section of https://wiki.mozilla.org/NSS:Release_Versions"
          path: "security/"
          commit-message: "cacerts: pull in updated certs from Mozilla"
          author: "eclipse-temurin-bot <temurin-bot@eclipse.org>"
