name: CA Certs Update
on:
  workflow_dispatch:
  schedule:
    # https://crontab.guru/every-night-at-midnight
    - cron: "0 0 * * *"

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  update_ca_certs:
    if: startsWith(github.repository, 'adoptium/')
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791
        with:
          persist-credentials: false

      - name: Run updater
        working-directory: ./security
        run: "./mk-ca-bundle.pl"

      - uses: gr2m/create-or-update-pull-request-action@dc1726cbf4dd3ce766af4ec29cfb660e0125e8ee
        env:
          GITHUB_TOKEN: ${{ secrets.ADOPTIUM_TEMURIN_BOT_TOKEN }}
        with:
          title: "Update CA Certs"
          body: "See details in the Meta Bug linked from the *Root Cert Inclusions into Mozilla Product Releases* section of https://wiki.mozilla.org/NSS:Release_Versions"
          path: "security/"
          commit-message: "cacerts: pull in updated certs from Mozilla"
          author: "eclipse-temurin-bot <temurin-bot@eclipse.org>"
